apiVersion: events.cloud.google.com/v1alpha1
kind: PubSub
metadata:
  name: watermark-document-source
spec:
  topic: watermark-document
  sink:
    apiVersion: eventing.knative.dev/v1alpha1
    kind: Broker
    name: default
