apiVersion: serving.knative.dev/v1 # Current version of Knative
kind: Service
metadata:
  name: ticketing_service # The name of the app
  namespace: default # The namespace the app will use
spec:
  template:
    spec:
      volumes:
        - name: service-account-credentials-volume
          secret:
            secretName: google-cloud-key
            items:
            - key: key.json 
              path: key.json
      containers:
        - image: kmjayadeep/watermark-ticketing-service
          env:
            - name: GOOGLE_APPLICATION_CREDENTIALS
              value: /etc/gcp/key.json
          volumeMounts:
            - name: service-account-credentials-volume
              mountPath: /etc/gcp
              readOnly: true